name: WDIO-CI
on:
  push:
    branches: [ master, release]
  pull_request:
    branches: [ master, release]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello world!
